services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8180:8080
    command: start-dev --import-realm
