services:
  keycloak:
    image: keycloak/keycloak
    command: start-dev --import-realm
    volumes:
      - ./data:/opt/keycloak/data
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: dev-file
    ports:
      - 8180:8080
