server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: ${KEY_STORE_FILE_PATH}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: defence-in-depth
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/defence-in-depth

