app:
  version: '@project.version@'
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: /home/erica/.local/share/mkcert/defence-in-depth.p12
    key-store-password: notasecretpassword
spring:
  application:
    name: defence-in-depth
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:4000/realms/defence-in-depth
  config:
    import:
      'optional:aws-secretsmanager:defence-in-depth'
aws:
  secretsmanager:
    region: eu-west-1